main.js, src/index.html, src/js/renderer.js
=> update Oct 5 frontend

main.js, package.json, preload.js, src/index.html, src/js/renderer.js
Added initial loading page if a user has no profile yet..
=> added initial page

main.js, src/index.html, src/js/renderer.js
- add bankers list in add banker tab
- add currency in Add banker
=> bankers list

main.js, src/js/renderer.js
Filter bankers with pubkey on create new contract
=> Filter bankers with pubkey on create new contract

main.js, src/index.html
=> upload text request pubkey

main.js, src/index.html
Fix aside id create user profile
=> fix aside id

main.js, src/index.html, src/js/renderer.js
Fix pubkey request on import text
=> request pubkey import

src/index.html, src/js/renderer.js
=> account details screen

main.js, src/index.html, src/js/renderer.js
withdrawal utxo api
init actions screen
clear text area on success response
=> withdrawal utxo api

main.js, src/index.html, src/js/renderer.js
=> add new banker message

main.js, src/js/renderer.js
=> initialize decodedRs

main.js, src/index.html, src/js/renderer.js
Add function to serialize input and output
Add function to verify script
=> withdraw reference

main.js, src/js/renderer.js
=> banker request signature js

src/index.html, src/js/renderer.js
=> banker sign tx init

src/index.html, src/js/renderer.js
sign transaction request message
=> sign transaction request message

src/index.html, src/js/renderer.js
Added function to handle multiple user input form.
function that sum lisunspent inputs
=> added add delete inputs

main.js, src/index.html, src/js/renderer.js
Added function for get unspent and user input
=> request signaturewindow

main.js, src/js/renderer.js
=> Update keys in json objects

main.js, src/js/renderer.js
Add funtion that will update contract signatures
=> update contract signature

main.js, src/index.html, src/js/coin.js, src/js/renderer.js
withdrawal broadcasting view
api call
=> withdrawal broadcasting

main.js, src/index.html, src/js/renderer.js
=> bug fixes for withdrawal flow

main.js
bug fixes for add banker tab initial launch
=> bug fixes for add banker tab initial launch

main.js
bug fix for creating new account on initial launch
=> bug fix for creating new account on initial launch

main.js, src/js/renderer.js
Bug fix for generating priv key
=> Bug fix for generating priv key

src/js/renderer.js
Add banker bug fix on initial lunch
undefined for user data in message
=> Add banker bug fix on initial lunch

main.js
Fix for withdrawal next banker signatory
=> Fix for withdrawal next banker signatory

main.js, src/js/renderer.js
=> sign tx bug fix

main.js, src/index.html, src/js/coin.js, src/js/renderer.js
private key generation in the add banker transaction
=> private key generation

src/js/renderer.js
change the validation for wif key
=> change the validation for wif key

src/index.html
aligning inputs on withdrawal page and button
=> october252023

src/index.html, src/js/renderer.js
Add change address if fee is more that 0.01
Add donation button
=> withdrawal update

main.js, package.json, src/index.html, src/input.css, src/js/renderer.js
fix choose bankers align css to js
=> fix choose bankers

main.js, src/index.html, src/js/renderer.js
=> import export data initial

src/index.html, src/js/renderer.js
show file directory when exporting, init
index html fix indentation and duplicate ids
=> show file directory when exporting, init

src/index.html, src/js/renderer.js
=> index indentation

src/index.html
=> fix white space bugs in index

src/index.html, src/js/renderer.js
hide List of bankers when navigating to other screen
Change all message styling. add font-normal text-base
Clear withdrawal request for signature message
Account details, Actions table
Remove Restore in the nav bar
=> account actions list

src/index.html, src/js/renderer.js
inputs field fixed, button fixed, inputs align fixed
=> newfixfornov4

src/index.html
about fscb text done, button every page fixed, margin and padding on every page done.
=> november07

src/index.html, src/js/bitcoin.js, src/js/bitellipticcurve.js, src/js/litecoin.js, src/js/litellipticcurve.js, src/js/renderer.js
bitcoin and litecoin coinjs and ellipticcurve 
bitcion and litecion keys generation in add banker
=> bitcoin and litecoin coinjs and ellipticcurve

main.js, src/index.html, src/js/renderer.js
filter banker based on currency in new account
=> filter banker based on currency in new account

main.js, src/js/renderer.js
Added bitcoin and litecoin on account list view.
=> add btc ltc on list

main.js, src/index.html, src/js/renderer.js
Added bitcoin and litecoin unspent API. adust function to show unspent
=> added btc and ltc unspent

src/js/renderer.js
sign transaction conditional statement
=> sign transaction conditional statement

main.js, src/js/renderer.js
coin js conditions for log, btc and lite
=> coin js conditions for log, btc and lite

main.js
coinditional broadcast for log, btc, ltc init -- for testing
=> coinditional broadcast for log, btc, ltc init

src/js/renderer.js
conditional statement for donation address
=> conditional statement for donation address

main.js, src/index.html
Change balance API and unspent
=> convert to chain so

main.js, src/js/renderer.js
sochain api unspent and broadcast for testing
=> sochain api unspent and broadcast

main.js
sochain fix error in api calls
=> sochain fix error in api calls

src/index.html, src/js/bitcoin.js, src/js/litecoin.js, src/js/renderer.js
coinjs newkeysfromhex function for ltc and btc
=> coinjs newkeysfromhex function for ltc and btc

main.js, src/index.html, src/js/renderer.js
select banker screen in withdrawal
=> select banker screen in withdrawal

main.js
main js fix for selecting new banker
=> main js fix for selecting new banker

src/index.html, src/js/renderer.js
refresh button in account list screen
=> refresh button in account list screen

main.js, src/js/renderer.js
checking for new account with same address and redeem script
=> checkin for new account with same address and redeem script

main.js, package.json
=> environment variable

src/index.html, src/js/renderer.js
Add a checker for max number of bankers in an account
=> Add a checker for max number of bankers in an account

src/js/renderer.js
=> centered copy button

main.js, src/js/renderer.js
=> Move data to fscb folder

main.js, src/index.html, src/js/renderer.js
=> Clean console logs

src/js/renderer.js
Add form input field sanitation
=> Add form input field sanitation

src/js/renderer.js
more valdations and readonly inputs
=> more valdations and readonly inputs
